export const questions = [
  {
    id: 1,
    question: "What does AI stand for?",
    options: [
      "A. Automated Intelligence",
      "B. Artificial Intelligence",
      "C. Analytical Integration",
      "D. Autonomous Interaction",
    ],
    correctAnswer: "B. Artificial Intelligence",
    category: "Artificial Intelligence",
    level: "Easy",
  },
  {
    id: 2,
    question: "Which of the following is a type of machine learning?",
    options: [
      "A. Supervised learning",
      "B. Manual learning",
      "C. Automated learning",
      "D. Systematic learning",
    ],
    correctAnswer: "A. Supervised learning",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 3,
    question: "What is a neural network?",
    options: [
      "A. A system of interconnected neurons",
      "B. A type of social network",
      "C. A network of computers",
      "D. A web of neural connections in the brain",
    ],
    correctAnswer: "A. A system of interconnected neurons",
    category: "Artificial Intelligence",
    level: "Hard",
  },
  {
    id: 4,
    question: "Which algorithm is commonly used in AI for decision making?",
    options: [
      "A. Genetic Algorithm",
      "B. Sorting Algorithm",
      "C. Binary Search Algorithm",
      "D. Data Compression Algorithm",
    ],
    correctAnswer: "A. Genetic Algorithm",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 5,
    question: "What is the Turing Test used for?",
    options: [
      "A. To test a computer's memory",
      "B. To determine if a machine can exhibit intelligent behavior",
      "C. To measure processing speed",
      "D. To evaluate software performance",
    ],
    correctAnswer:
      "B. To determine if a machine can exhibit intelligent behavior",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 6,
    question:
      "Which of the following is an example of natural language processing?",
    options: [
      "A. Speech recognition",
      "B. Image classification",
      "C. Data mining",
      "D. Network security",
    ],
    correctAnswer: "A. Speech recognition",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 7,
    question: "What does the term 'overfitting' mean in machine learning?",
    options: [
      "A. Model is too simple",
      "B. Model performs well on training data but poorly on new data",
      "C. Model learns too slowly",
      "D. Model is too large to process",
    ],
    correctAnswer:
      "B. Model performs well on training data but poorly on new data",
    category: "Artificial Intelligence",
    level: "Hard",
  },
  {
    id: 8,
    question: "Which company is known for its AI research and development?",
    options: ["A. Google", "B. Facebook", "C. Amazon", "D. All of the above"],
    correctAnswer: "D. All of the above",
    category: "Artificial Intelligence",
    level: "Easy",
  },
  {
    id: 9,
    question: "What is deep learning?",
    options: [
      "A. A type of unsupervised learning",
      "B. A subfield of machine learning that uses neural networks",
      "C. A method for data visualization",
      "D. A strategy for data collection",
    ],
    correctAnswer:
      "B. A subfield of machine learning that uses neural networks",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 10,
    question: "What does reinforcement learning involve?",
    options: [
      "A. Learning from labeled data",
      "B. Learning through trial and error",
      "C. Learning by imitation",
      "D. Learning from direct instructions",
    ],
    correctAnswer: "B. Learning through trial and error",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 11,
    question: "Which of the following is a common application of AI?",
    options: [
      "A. Image recognition",
      "B. Sentiment analysis",
      "C. Autonomous vehicles",
      "D. All of the above",
    ],
    correctAnswer: "D. All of the above",
    category: "Artificial Intelligence",
    level: "Easy",
  },
  {
    id: 12,
    question: "What is the main goal of artificial intelligence?",
    options: [
      "A. To mimic human intelligence",
      "B. To create social networks",
      "C. To improve hardware",
      "D. To enhance graphics",
    ],
    correctAnswer: "A. To mimic human intelligence",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 13,
    question: "Which programming language is most commonly associated with AI?",
    options: ["A. JavaScript", "B. Python", "C. HTML", "D. CSS"],
    correctAnswer: "B. Python",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 14,
    question: "What is a chatbot?",
    options: [
      "A. A robot that cleans your house",
      "B. A software application used to conduct an online chat",
      "C. A game for children",
      "D. A type of social media platform",
    ],
    correctAnswer: "B. A software application used to conduct an online chat",
    category: "Artificial Intelligence",
    level: "Easy",
  },
  {
    id: 15,
    question: "What is machine vision?",
    options: [
      "A. The ability to see machines",
      "B. A field of AI that enables machines to interpret visual data",
      "C. A method of training robots",
      "D. The process of creating virtual reality",
    ],
    correctAnswer:
      "B. A field of AI that enables machines to interpret visual data",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 16,
    question: "What is a key benefit of using AI in healthcare?",
    options: [
      "A. Reducing paperwork",
      "B. Automating insurance claims",
      "C. Enhancing diagnostic accuracy",
      "D. Lowering staff salaries",
    ],
    correctAnswer: "C. Enhancing diagnostic accuracy",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 17,
    question: "What is a primary concern regarding AI?",
    options: [
      "A. Improved efficiency",
      "B. Job displacement",
      "C. Enhanced security",
      "D. Faster processing",
    ],
    correctAnswer: "B. Job displacement",
    category: "Artificial Intelligence",
    level: "Hard",
  },
  {
    id: 18,
    question: "What is the purpose of a recommendation system?",
    options: [
      "A. To generate random product suggestions",
      "B. To analyze customer behavior and suggest products",
      "C. To monitor social media",
      "D. To enhance website traffic",
    ],
    correctAnswer: "B. To analyze customer behavior and suggest products",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 19,
    question: "What does the acronym 'NLP' stand for?",
    options: [
      "A. Natural Language Programming",
      "B. Neural Language Processing",
      "C. Natural Language Processing",
      "D. Non-linear Programming",
    ],
    correctAnswer: "C. Natural Language Processing",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 20,
    question: "What is an AI bias?",
    options: [
      "A. A type of software bug",
      "B. An unfair discrimination in AI algorithms",
      "C. A measure of an AI's performance",
      "D. A tool for data analysis",
    ],
    correctAnswer: "B. An unfair discrimination in AI algorithms",
    category: "Artificial Intelligence",
    level: "Hard",
  },
  {
    id: 21,
    question: "Which of the following best describes 'Big Data'?",
    options: [
      "A. Large volumes of structured and unstructured data",
      "B. A type of programming language",
      "C. A network of interconnected devices",
      "D. A social media platform",
    ],
    correctAnswer: "A. Large volumes of structured and unstructured data",
    category: "Artificial Intelligence",
    level: "Easy",
  },
  {
    id: 22,
    question: "What is the primary purpose of computer vision?",
    options: [
      "A. To enable computers to interpret visual information",
      "B. To create 3D graphics",
      "C. To enhance online security",
      "D. To reduce data storage",
    ],
    correctAnswer: "A. To enable computers to interpret visual information",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 23,
    question: "Which AI application is commonly used in e-commerce?",
    options: [
      "A. Virtual reality",
      "B. Fraud detection",
      "C. Network monitoring",
      "D. Social media management",
    ],
    correctAnswer: "B. Fraud detection",
    category: "Artificial Intelligence",
    level: "Medium",
  },
  {
    id: 24,
    question: "What is 'transfer learning'?",
    options: [
      "A. Transferring data between devices",
      "B. Applying knowledge from one task to another",
      "C. Moving machine learning models to the cloud",
      "D. Learning from human teachers",
    ],
    correctAnswer: "B. Applying knowledge from one task to another",
    category: "Artificial Intelligence",
    level: "Hard",
  },
  {
    id: 25,
    question: "Which of the following is a characteristic of AI?",
    options: [
      "A. Ability to learn from experience",
      "B. Ability to work without human intervention",
      "C. Ability to process large amounts of data",
      "D. All of the above",
    ],
    correctAnswer: "D. All of the above",
    category: "Artificial Intelligence",
    level: "Easy",
  },
  {
    id: 26,
    question: "What is the chemical symbol for water?",
    options: ["A. H2O", "B. O2H", "C. HO2", "D. H2O2"],
    correctAnswer: "A. H2O",
    category: "Science",
    level: "Easy",
  },
  {
    id: 27,
    question: "What is the powerhouse of the cell?",
    options: [
      "A. Nucleus",
      "B. Ribosome",
      "C. Mitochondria",
      "D. Endoplasmic Reticulum",
    ],
    correctAnswer: "C. Mitochondria",
    category: "Science",
    level: "Easy",
  },
  {
    id: 28,
    question: "What gas do plants absorb from the atmosphere?",
    options: ["A. Oxygen", "B. Nitrogen", "C. Carbon Dioxide", "D. Hydrogen"],
    correctAnswer: "C. Carbon Dioxide",
    category: "Science",
    level: "Easy",
  },
  {
    id: 29,
    question: "What is the main component of the Earth's atmosphere?",
    options: ["A. Oxygen", "B. Carbon Dioxide", "C. Nitrogen", "D. Argon"],
    correctAnswer: "C. Nitrogen",
    category: "Science",
    level: "Easy",
  },
  {
    id: 30,
    question: "Which planet is known as the Red Planet?",
    options: ["A. Earth", "B. Mars", "C. Jupiter", "D. Venus"],
    correctAnswer: "B. Mars",
    category: "Science",
    level: "Easy",
  },
  {
    id: 31,
    question: "What is the boiling point of water?",
    options: ["A. 100°C", "B. 0°C", "C. 50°C", "D. 200°C"],
    correctAnswer: "A. 100°C",
    category: "Science",
    level: "Easy",
  },
  {
    id: 32,
    question:
      "Which part of the brain is responsible for coordinating movement?",
    options: ["A. Cerebrum", "B. Cerebellum", "C. Brainstem", "D. Thalamus"],
    correctAnswer: "B. Cerebellum",
    category: "Science",
    level: "Medium",
  },
  {
    id: 33,
    question: "What type of bond involves the sharing of electron pairs?",
    options: [
      "A. Ionic bond",
      "B. Covalent bond",
      "C. Hydrogen bond",
      "D. Metallic bond",
    ],
    correctAnswer: "B. Covalent bond",
    category: "Science",
    level: "Medium",
  },
  {
    id: 34,
    question: "What is the process by which plants make their food?",
    options: [
      "A. Respiration",
      "B. Photosynthesis",
      "C. Digestion",
      "D. Fermentation",
    ],
    correctAnswer: "B. Photosynthesis",
    category: "Science",
    level: "Easy",
  },
  {
    id: 35,
    question: "What is the largest organ in the human body?",
    options: ["A. Heart", "B. Brain", "C. Skin", "D. Liver"],
    correctAnswer: "C. Skin",
    category: "Science",
    level: "Medium",
  },
  {
    id: 36,
    question: "What is the chemical formula for table salt?",
    options: ["A. NaCl", "B. KCl", "C. CaCl2", "D. MgCl2"],
    correctAnswer: "A. NaCl",
    category: "Science",
    level: "Easy",
  },
  {
    id: 37,
    question: "What is the main gas found in the Sun?",
    options: ["A. Oxygen", "B. Helium", "C. Hydrogen", "D. Nitrogen"],
    correctAnswer: "C. Hydrogen",
    category: "Science",
    level: "Easy",
  },
  {
    id: 38,
    question: "What is the basic unit of life?",
    options: ["A. Tissue", "B. Organ", "C. Cell", "D. Organism"],
    correctAnswer: "C. Cell",
    category: "Science",
    level: "Easy",
  },
  {
    id: 39,
    question: "Which of the following is not a planet in our solar system?",
    options: ["A. Venus", "B. Pluto", "C. Proxima Centauri", "D. Jupiter"],
    correctAnswer: "C. Proxima Centauri",
    category: "Science",
    level: "Medium",
  },
  {
    id: 40,
    question: "What is the pH level of pure water?",
    options: ["A. 0", "B. 7", "C. 14", "D. 10"],
    correctAnswer: "B. 7",
    category: "Science",
    level: "Easy",
  },
  {
    id: 41,
    question: "What type of radiation is emitted by the Sun?",
    options: [
      "A. Gamma rays",
      "B. X-rays",
      "C. Ultraviolet radiation",
      "D. Infrared radiation",
    ],
    correctAnswer: "C. Ultraviolet radiation",
    category: "Science",
    level: "Medium",
  },
  {
    id: 42,
    question: "What is the most abundant gas in the Earth's atmosphere?",
    options: ["A. Carbon Dioxide", "B. Oxygen", "C. Nitrogen", "D. Argon"],
    correctAnswer: "C. Nitrogen",
    category: "Science",
    level: "Easy",
  },
  {
    id: 43,
    question: "What is the study of living organisms called?",
    options: ["A. Chemistry", "B. Biology", "C. Physics", "D. Geology"],
    correctAnswer: "B. Biology",
    category: "Science",
    level: "Easy",
  },
  {
    id: 44,
    question: "Which planet is known for its rings?",
    options: ["A. Mars", "B. Saturn", "C. Jupiter", "D. Neptune"],
    correctAnswer: "B. Saturn",
    category: "Science",
    level: "Easy",
  },
  {
    id: 45,
    question: "What is the primary function of red blood cells?",
    options: [
      "A. To fight infection",
      "B. To carry oxygen",
      "C. To clot blood",
      "D. To transport nutrients",
    ],
    correctAnswer: "B. To carry oxygen",
    category: "Science",
    level: "Medium",
  },
  {
    id: 46,
    question: "Which of the following is a renewable source of energy?",
    options: [
      "A. Coal",
      "B. Natural Gas",
      "C. Solar Power",
      "D. Nuclear Power",
    ],
    correctAnswer: "C. Solar Power",
    category: "Science",
    level: "Medium",
  },
  {
    id: 47,
    question:
      "What is the process by which living organisms adapt to their environment?",
    options: [
      "A. Evolution",
      "B. Inheritance",
      "C. Reproduction",
      "D. Mutation",
    ],
    correctAnswer: "A. Evolution",
    category: "Science",
    level: "Hard",
  },
  {
    id: 48,
    question: "What is the main organ involved in the circulatory system?",
    options: ["A. Lung", "B. Heart", "C. Kidney", "D. Brain"],
    correctAnswer: "B. Heart",
    category: "Science",
    level: "Easy",
  },
  {
    id: 49,
    question: "What is the smallest unit of matter?",
    options: ["A. Molecule", "B. Atom", "C. Cell", "D. Compound"],
    correctAnswer: "B. Atom",
    category: "Science",
    level: "Easy",
  },
  {
    id: 50,
    question: "What type of organism is an eagle?",
    options: ["A. Mammal", "B. Reptile", "C. Bird", "D. Amphibian"],
    correctAnswer: "C. Bird",
    category: "Science",
    level: "Easy",
  },
  {
    id: 51,
    question: "What is the capital city of France?",
    options: ["A. Rome", "B. Paris", "C. Berlin", "D. Madrid"],
    correctAnswer: "B. Paris",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 52,
    question: "Who wrote 'Hamlet'?",
    options: [
      "A. Charles Dickens",
      "B. William Shakespeare",
      "C. Mark Twain",
      "D. Jane Austen",
    ],
    correctAnswer: "B. William Shakespeare",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 53,
    question: "What is the largest ocean on Earth?",
    options: [
      "A. Atlantic Ocean",
      "B. Indian Ocean",
      "C. Arctic Ocean",
      "D. Pacific Ocean",
    ],
    correctAnswer: "D. Pacific Ocean",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 54,
    question: "What is the currency of Japan?",
    options: ["A. Dollar", "B. Euro", "C. Yen", "D. Won"],
    correctAnswer: "C. Yen",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 55,
    question: "In which year did the Titanic sink?",
    options: ["A. 1912", "B. 1905", "C. 1920", "D. 1898"],
    correctAnswer: "A. 1912",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 56,
    question: "Which planet is known as the 'Blue Planet'?",
    options: ["A. Mars", "B. Earth", "C. Neptune", "D. Uranus"],
    correctAnswer: "B. Earth",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 57,
    question: "Who painted the Mona Lisa?",
    options: [
      "A. Vincent van Gogh",
      "B. Pablo Picasso",
      "C. Leonardo da Vinci",
      "D. Claude Monet",
    ],
    correctAnswer: "C. Leonardo da Vinci",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 58,
    question: "What is the tallest mountain in the world?",
    options: ["A. K2", "B. Kangchenjunga", "C. Mount Everest", "D. Lhotse"],
    correctAnswer: "C. Mount Everest",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 59,
    question: "Which gas do humans breathe in to survive?",
    options: ["A. Carbon Dioxide", "B. Oxygen", "C. Nitrogen", "D. Helium"],
    correctAnswer: "B. Oxygen",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 60,
    question: "What is the smallest country in the world?",
    options: [
      "A. Monaco",
      "B. Vatican City",
      "C. San Marino",
      "D. Liechtenstein",
    ],
    correctAnswer: "B. Vatican City",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 61,
    question: "What is the main ingredient in guacamole?",
    options: ["A. Tomato", "B. Avocado", "C. Onion", "D. Pepper"],
    correctAnswer: "B. Avocado",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 62,
    question: "What is the longest river in the world?",
    options: ["A. Nile", "B. Amazon", "C. Yangtze", "D. Mississippi"],
    correctAnswer: "B. Amazon",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 63,
    question: "Which country is known as the land of the rising sun?",
    options: ["A. China", "B. Japan", "C. South Korea", "D. Thailand"],
    correctAnswer: "B. Japan",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 64,
    question: "Which is the largest continent?",
    options: ["A. Africa", "B. Asia", "C. Europe", "D. Antarctica"],
    correctAnswer: "B. Asia",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 65,
    question: "Who is known as the father of modern physics?",
    options: [
      "A. Isaac Newton",
      "B. Albert Einstein",
      "C. Galileo Galilei",
      "D. Niels Bohr",
    ],
    correctAnswer: "B. Albert Einstein",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 66,
    question: "What is the most widely spoken language in the world?",
    options: ["A. English", "B. Mandarin Chinese", "C. Spanish", "D. Hindi"],
    correctAnswer: "B. Mandarin Chinese",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 67,
    question: "What is the main organ of the human circulatory system?",
    options: ["A. Brain", "B. Heart", "C. Lungs", "D. Liver"],
    correctAnswer: "B. Heart",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 68,
    question: "Which ocean is the largest?",
    options: [
      "A. Atlantic Ocean",
      "B. Indian Ocean",
      "C. Arctic Ocean",
      "D. Pacific Ocean",
    ],
    correctAnswer: "D. Pacific Ocean",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 69,
    question: "In which year did World War II end?",
    options: ["A. 1945", "B. 1939", "C. 1942", "D. 1950"],
    correctAnswer: "A. 1945",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 70,
    question: "Who invented the telephone?",
    options: [
      "A. Thomas Edison",
      "B. Alexander Graham Bell",
      "C. Nikola Tesla",
      "D. Guglielmo Marconi",
    ],
    correctAnswer: "B. Alexander Graham Bell",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 71,
    question: "What is the hardest natural substance on Earth?",
    options: ["A. Gold", "B. Diamond", "C. Iron", "D. Quartz"],
    correctAnswer: "B. Diamond",
    category: "General Knowledge",
    level: "Hard",
  },
  {
    id: 72,
    question: "Which planet is known as the Red Planet?",
    options: ["A. Mars", "B. Jupiter", "C. Saturn", "D. Venus"],
    correctAnswer: "A. Mars",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 73,
    question: "What is the chemical symbol for gold?",
    options: ["A. Ag", "B. Au", "C. Pb", "D. Fe"],
    correctAnswer: "B. Au",
    category: "General Knowledge",
    level: "Medium",
  },
  {
    id: 74,
    question: "What is the largest mammal in the world?",
    options: [
      "A. African Elephant",
      "B. Blue Whale",
      "C. Giraffe",
      "D. Hippopotamus",
    ],
    correctAnswer: "B. Blue Whale",
    category: "General Knowledge",
    level: "Easy",
  },
  {
    id: 75,
    question: "Who discovered penicillin?",
    options: [
      "A. Louis Pasteur",
      "B. Alexander Fleming",
      "C. Marie Curie",
      "D. Thomas Edison",
    ],
    correctAnswer: "B. Alexander Fleming",
    category: "General Knowledge",
    level: "Medium",
  },
];
